"""Generate an Obsidian-friendly Markdown review file from annotations."""

import json
import os
from pathlib import Path

from . import paths

def generate_review_md() -> None:
    if not paths.COT_ANNOTATIONS.exists():
        print("No annotations found. Run the pipeline first.")
        return


    out_path = paths.OUTPUTS / "review.md"
    lines = [
        "# Annotation Review",
        "",
        "This file is generated by `uv run python -m pipeline.visualize`. ",
        "It is designed to be viewed inside Obsidian to see the image alongside the generated CoT.",
        "",
    ]

    annotations = []
    for path in paths.COT_ANNOTATIONS.rglob("*.json"):

        try:
            ann = json.loads(path.read_text(encoding="utf-8"))
            annotations.append(ann)
        except json.JSONDecodeError:
            continue

    if not annotations:
        print("No valid annotations found.")
        return

    # Group by label
    grouped = {}
    for ann in annotations:
        label = ann.get("label", "unknown")
        grouped.setdefault(label, []).append(ann)

    for label in sorted(grouped.keys()):
        lines.extend([f"## Category: {label}", ""])
        for ann in sorted(grouped[label], key=lambda x: x.get("image_id", "")):
            image_id = ann.get("image_id")
            image_path = ann.get("image_path")
            if image_path:
                img_p = Path(image_path)
                # If the stored path doesn't exist, try to find it under data/
                if not (paths.ROOT / img_p).exists():
                    matches = list(paths.DATA.rglob(img_p.name))
                    if matches:
                        # Use the first match relative to ROOT
                        image_path = str(matches[0].relative_to(paths.ROOT))
            
            # Calculate relative path from the review file to ROOT
            # If out_path is outputs/split/review.md, parent is outputs/split
            # Relative path to ROOT is ../../
            try:
                rel_to_root = os.path.relpath(paths.ROOT, out_path.parent)
            except ValueError:
                rel_to_root = ".." # fallback
            
            rel_image = f"{rel_to_root}/{image_path}" if image_path else ""
            
            gt = ann.get("gt_answer", "")
            modality = ann.get("modality", "")
            difficulty = ann.get("difficulty", "")
            bbox = ann.get("subject_bbox", [])
            cot = ann.get("cot", "")
            
            # Formatting bbox string nicely
            bbox_str = f"[{bbox[0]:.2f}, {bbox[1]:.2f}, {bbox[2]:.2f}, {bbox[3]:.2f}]" if len(bbox) == 4 else str(bbox)

            lines.extend([
                f"### {image_id}",
                f"**GT:** `{gt}` | **Modality:** `{modality}` | **Difficulty:** `{difficulty}` | **BBox:** `{bbox_str}`",
                "",
                f"![{image_id}]({rel_image})",
                "",
                "**CoT:**",
                f"> {cot}",
                "",
                "---",
                ""
            ])

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {out_path.relative_to(paths.ROOT)} with {len(annotations)} annotations.")
    print("Open this file in Obsidian to review!")

def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description="Generate an Obsidian review file.")
    parser.add_argument("--split", type=str, default=None, help="Process a specific data split")
    args = parser.parse_args()

    if args.split:
        paths.set_split(args.split)
        # Ensure directories exist for this split if we're generating outputs there
        paths.ensure_dirs()

    generate_review_md()

if __name__ == "__main__":
    main()

