"""Generate an Obsidian-friendly Markdown review file from annotations."""

import json
from pathlib import Path

from . import paths

def generate_review_md() -> None:
    if not paths.ANNOTATIONS.exists():
        print("No annotations found. Run the pipeline first.")
        return

    out_path = paths.OUTPUTS / "review.md"
    lines = [
        "# Annotation Review",
        "",
        "This file is generated by `uv run python -m pipeline.visualize`. ",
        "It is designed to be viewed inside Obsidian to see the image alongside the generated CoT.",
        "",
    ]

    annotations = []
    for path in paths.ANNOTATIONS.rglob("*.json"):
        try:
            ann = json.loads(path.read_text(encoding="utf-8"))
            annotations.append(ann)
        except json.JSONDecodeError:
            continue

    if not annotations:
        print("No valid annotations found.")
        return

    # Group by label
    grouped = {}
    for ann in annotations:
        label = ann.get("label", "unknown")
        grouped.setdefault(label, []).append(ann)

    for label in sorted(grouped.keys()):
        lines.extend([f"## Category: {label}", ""])
        for ann in sorted(grouped[label], key=lambda x: x.get("image_id", "")):
            image_id = ann.get("image_id")
            image_path = ann.get("image_path")
            
            # Obsidian image link syntax or standard markdown
            # Using standard markdown so it works everywhere, but pointing relative to outputs/
            # The image path in annotation is relative to ROOT. 
            # We are writing to ROOT/outputs/review.md, so relative path to image is ../image_path
            rel_image = f"../{image_path}"
            
            gt = ann.get("gt_answer", "")
            modality = ann.get("modality", "")
            difficulty = ann.get("difficulty", "")
            bbox = ann.get("subject_bbox", [])
            cot = ann.get("cot", "")
            
            # Formatting bbox string nicely
            bbox_str = f"[{bbox[0]:.2f}, {bbox[1]:.2f}, {bbox[2]:.2f}, {bbox[3]:.2f}]" if len(bbox) == 4 else str(bbox)

            lines.extend([
                f"### {image_id}",
                f"**GT:** `{gt}` | **Modality:** `{modality}` | **Difficulty:** `{difficulty}` | **BBox:** `{bbox_str}`",
                "",
                f"![{image_id}]({rel_image})",
                "",
                "**CoT:**",
                f"> {cot}",
                "",
                "---",
                ""
            ])

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {out_path.relative_to(paths.ROOT)} with {len(annotations)} annotations.")
    print("Open this file in Obsidian to review!")

def main() -> None:
    generate_review_md()

if __name__ == "__main__":
    main()
